# Generated by Django 4.2.4 on 2023-12-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
